### ISSUE TITLE
arduino library submission

### ISSUE THREAD

**Issue by pacav69** [ubidots/ubidots-mqtt-esp#10]
Hi,
I think this a great library and i submitted a request to add to the library manager and this is their response

>> You need to create a release or tag that matches the version value in your library.properties file.

More information
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

Submit issue
https://github.com/arduino/Arduino/issues

**Comment by jotathebest** [comment]
Hi there, I have just added a new tag with the actual version.

All the best

**Comment by pacav69** [comment]
great i have processed the library :)

**Comment by pacav69** [comment]
the library has now been added to arduino's library manager
https://github.com/arduino/Arduino/issues/7345#issuecomment-374181493

**Comment by jotathebest** [comment]
closing
