### ISSUE TITLE
[REQUEST] Support for the new Sonoff RF Bridge 433

### ISSUE THREAD

**Issue by Gamester17** [ubidots/ubidots-mqtt-esp#9]
Request firmware support for the new Sonoff RF Bridge 433

https://www.itead.cc/sonoff-rf-bridge-433.html

WiFi to 433MHz converter and vice versa to convert 433MHz RF sensors and remote to App via WiFi

https://www.itead.cc/wiki/Sonoff_RF_Bridge_433

Based on ESP8285 (ESP8266 chipset) from Itead.

https://www.youtube.com/watch?v=wTqQ_cmweuo

**Comment by jotathebest** [comment]
Greetings sir, what you expose to us is not an issue, it is a suggestion so I will proceed to close this thread.

About your suggestion, unfortunately we do not plan to support the device specified by you in the long term.

Let us to know if you have any additional doubt or suggest.

Regards
